<?php

namespace Database\Seeders;

use App\Models\SimpleQuestion;
use Illuminate\Database\Seeder;

class SimpleQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Science (1-50)
            ['question' => 'What is the chemical symbol for gold?', 'answer' => 'Au (from Latin: aurum)'],
            ['question' => 'What is the speed of light in a vacuum?', 'answer' => 'Approximately 299,792,458 meters per second or 186,282 miles per second'],
            ['question' => 'What is the largest organ in the human body?', 'answer' => 'The skin'],
            ['question' => 'How many bones are in the adult human body?', 'answer' => '206 bones'],
            ['question' => 'What planet is known as the Red Planet?', 'answer' => 'Mars'],
            ['question' => 'What is the hardest natural substance on Earth?', 'answer' => 'Diamond'],
            ['question' => 'What is H2O?', 'answer' => 'Water'],
            ['question' => 'What is the powerhouse of the cell?', 'answer' => 'The mitochondria'],
            ['question' => 'What gas do plants absorb from the atmosphere?', 'answer' => 'Carbon dioxide (CO2)'],
            ['question' => 'What is the smallest unit of life?', 'answer' => 'The cell'],
            ['question' => 'What is the study of earthquakes called?', 'answer' => 'Seismology'],
            ['question' => 'What is the boiling point of water in Celsius?', 'answer' => '100 degrees Celsius at sea level'],
            ['question' => 'What is the most abundant gas in Earth\'s atmosphere?', 'answer' => 'Nitrogen (about 78%)'],
            ['question' => 'What is DNA an abbreviation for?', 'answer' => 'Deoxyribonucleic acid'],
            ['question' => 'How many chambers does the human heart have?', 'answer' => 'Four chambers (two atria and two ventricles)'],
            ['question' => 'What is the closest star to Earth?', 'answer' => 'The Sun'],
            ['question' => 'What is the study of fungi called?', 'answer' => 'Mycology'],
            ['question' => 'What element has the atomic number 1?', 'answer' => 'Hydrogen'],
            ['question' => 'What is the largest planet in our solar system?', 'answer' => 'Jupiter'],
            ['question' => 'What is the process by which plants make their food?', 'answer' => 'Photosynthesis'],
            ['question' => 'What is the smallest bone in the human body?', 'answer' => 'The stapes (stirrup bone in the ear)'],
            ['question' => 'What is the freezing point of water in Fahrenheit?', 'answer' => '32 degrees Fahrenheit'],
            ['question' => 'What is the study of the weather called?', 'answer' => 'Meteorology'],
            ['question' => 'How many teeth does an adult human have?', 'answer' => '32 teeth'],
            ['question' => 'What is the largest moon of Saturn?', 'answer' => 'Titan'],
            ['question' => 'What is the chemical formula for table salt?', 'answer' => 'NaCl (sodium chloride)'],
            ['question' => 'What type of animal is a Komodo dragon?', 'answer' => 'A lizard (the largest living species of lizard)'],
            ['question' => 'What is the study of birds called?', 'answer' => 'Ornithology'],
            ['question' => 'What is the rarest blood type?', 'answer' => 'AB negative'],
            ['question' => 'How many elements are in the periodic table?', 'answer' => '118 confirmed elements'],
            ['question' => 'What is the speed of sound called?', 'answer' => 'Mach 1'],
            ['question' => 'What is the hottest planet in our solar system?', 'answer' => 'Venus'],
            ['question' => 'What is the study of insects called?', 'answer' => 'Entomology'],
            ['question' => 'What part of the brain controls balance?', 'answer' => 'The cerebellum'],
            ['question' => 'What is the chemical symbol for iron?', 'answer' => 'Fe (from Latin: ferrum)'],
            ['question' => 'How long does it take for light from the Sun to reach Earth?', 'answer' => 'Approximately 8 minutes and 20 seconds'],
            ['question' => 'What is the largest internal organ?', 'answer' => 'The liver'],
            ['question' => 'What is the study of stars and celestial bodies?', 'answer' => 'Astronomy'],
            ['question' => 'What is the main gas in the Sun?', 'answer' => 'Hydrogen'],
            ['question' => 'How many planets are in our solar system?', 'answer' => 'Eight planets'],
            ['question' => 'What is the study of the human mind called?', 'answer' => 'Psychology'],
            ['question' => 'What is the chemical symbol for silver?', 'answer' => 'Ag (from Latin: argentum)'],
            ['question' => 'What is the largest artery in the human body?', 'answer' => 'The aorta'],
            ['question' => 'What is the unit of electric current?', 'answer' => 'Ampere (or amp)'],
            ['question' => 'What is the smallest planet in our solar system?', 'answer' => 'Mercury'],
            ['question' => 'What is the study of rocks called?', 'answer' => 'Petrology'],
            ['question' => 'What is the only metal that is liquid at room temperature?', 'answer' => 'Mercury'],
            ['question' => 'What is the longest bone in the human body?', 'answer' => 'The femur (thigh bone)'],
            ['question' => 'What is the term for animals that eat both plants and meat?', 'answer' => 'Omnivores'],
            ['question' => 'What is the pH of pure water?', 'answer' => '7 (neutral)'],

            // History (51-100)
            ['question' => 'In what year did World War II end?', 'answer' => '1945'],
            ['question' => 'Who was the first President of the United States?', 'answer' => 'George Washington'],
            ['question' => 'What year did the Titanic sink?', 'answer' => '1912'],
            ['question' => 'Who painted the Mona Lisa?', 'answer' => 'Leonardo da Vinci'],
            ['question' => 'What ancient wonder is the only one still standing?', 'answer' => 'The Great Pyramid of Giza'],
            ['question' => 'In what year did Christopher Columbus reach the Americas?', 'answer' => '1492'],
            ['question' => 'Who was the first person to walk on the moon?', 'answer' => 'Neil Armstrong'],
            ['question' => 'What year did the Berlin Wall fall?', 'answer' => '1989'],
            ['question' => 'Who was the ancient Greek god of the sea?', 'answer' => 'Poseidon'],
            ['question' => 'What year did World War I begin?', 'answer' => '1914'],
            ['question' => 'Who invented the light bulb?', 'answer' => 'Thomas Edison (though others contributed to its development)'],
            ['question' => 'What empire was ruled by Julius Caesar?', 'answer' => 'The Roman Empire'],
            ['question' => 'In what year did the American Civil War end?', 'answer' => '1865'],
            ['question' => 'Who was the first woman to win a Nobel Prize?', 'answer' => 'Marie Curie'],
            ['question' => 'What year was the Declaration of Independence signed?', 'answer' => '1776'],
            ['question' => 'Who was the Egyptian queen famous for her relationship with Mark Antony?', 'answer' => 'Cleopatra'],
            ['question' => 'What ship did the Pilgrims sail on to America?', 'answer' => 'The Mayflower'],
            ['question' => 'Who invented the telephone?', 'answer' => 'Alexander Graham Bell'],
            ['question' => 'What year did the stock market crash, starting the Great Depression?', 'answer' => '1929'],
            ['question' => 'Who was the longest-reigning British monarch?', 'answer' => 'Queen Elizabeth II (70 years)'],
            ['question' => 'What year was the internet invented?', 'answer' => '1969 (ARPANET, the precursor to the internet)'],
            ['question' => 'Who was the leader of Nazi Germany?', 'answer' => 'Adolf Hitler'],
            ['question' => 'What year did the United States land the first man on the moon?', 'answer' => '1969'],
            ['question' => 'Who wrote the Communist Manifesto?', 'answer' => 'Karl Marx and Friedrich Engels'],
            ['question' => 'What was the name of the first atomic bomb dropped on Japan?', 'answer' => 'Little Boy (dropped on Hiroshima)'],
            ['question' => 'Who was the first Roman Emperor?', 'answer' => 'Augustus Caesar'],
            ['question' => 'What year was the Magna Carta signed?', 'answer' => '1215'],
            ['question' => 'Who discovered penicillin?', 'answer' => 'Alexander Fleming'],
            ['question' => 'What ancient city was buried by the eruption of Mount Vesuvius?', 'answer' => 'Pompeii'],
            ['question' => 'Who was the leader of the Soviet Union during World War II?', 'answer' => 'Joseph Stalin'],
            ['question' => 'What year did India gain independence from Britain?', 'answer' => '1947'],
            ['question' => 'Who was known as the "Iron Lady"?', 'answer' => 'Margaret Thatcher'],
            ['question' => 'What year was the French Revolution?', 'answer' => '1789'],
            ['question' => 'Who was the first president to resign from office?', 'answer' => 'Richard Nixon'],
            ['question' => 'What empire did Genghis Khan found?', 'answer' => 'The Mongol Empire'],
            ['question' => 'What year did Alaska become a U.S. state?', 'answer' => '1959'],
            ['question' => 'Who was the Greek god of war?', 'answer' => 'Ares'],
            ['question' => 'What was the name of the ship that brought the first settlers to Jamestown?', 'answer' => 'The Susan Constant, Godspeed, and Discovery'],
            ['question' => 'Who invented the airplane?', 'answer' => 'The Wright Brothers (Orville and Wilbur Wright)'],
            ['question' => 'What year was the Constitution ratified?', 'answer' => '1788'],
            ['question' => 'Who was the youngest U.S. President?', 'answer' => 'Theodore Roosevelt (at 42 years old)'],
            ['question' => 'What year did the Cold War end?', 'answer' => '1991'],
            ['question' => 'Who built the first automobile?', 'answer' => 'Karl Benz'],
            ['question' => 'What ancient civilization built Machu Picchu?', 'answer' => 'The Inca Empire'],
            ['question' => 'What year was the Louisiana Purchase?', 'answer' => '1803'],
            ['question' => 'Who was the first emperor of China?', 'answer' => 'Qin Shi Huang'],
            ['question' => 'What year did the Soviet Union dissolve?', 'answer' => '1991'],
            ['question' => 'Who assassinated President Abraham Lincoln?', 'answer' => 'John Wilkes Booth'],
            ['question' => 'What year was Pearl Harbor attacked?', 'answer' => '1941'],
            ['question' => 'Who was the first female Prime Minister of the UK?', 'answer' => 'Margaret Thatcher'],

            // Geography (101-150)
            ['question' => 'What is the capital of France?', 'answer' => 'Paris'],
            ['question' => 'What is the largest country by land area?', 'answer' => 'Russia'],
            ['question' => 'What is the longest river in the world?', 'answer' => 'The Nile River'],
            ['question' => 'What is the smallest country in the world?', 'answer' => 'Vatican City'],
            ['question' => 'What is the capital of Japan?', 'answer' => 'Tokyo'],
            ['question' => 'What mountain range separates Europe from Asia?', 'answer' => 'The Ural Mountains'],
            ['question' => 'What is the largest ocean on Earth?', 'answer' => 'The Pacific Ocean'],
            ['question' => 'What is the capital of Australia?', 'answer' => 'Canberra'],
            ['question' => 'How many continents are there?', 'answer' => 'Seven continents'],
            ['question' => 'What is the tallest mountain in the world?', 'answer' => 'Mount Everest'],
            ['question' => 'What is the capital of Canada?', 'answer' => 'Ottawa'],
            ['question' => 'What desert is the largest hot desert in the world?', 'answer' => 'The Sahara Desert'],
            ['question' => 'What is the capital of Brazil?', 'answer' => 'Brasília'],
            ['question' => 'What is the deepest ocean trench?', 'answer' => 'The Mariana Trench'],
            ['question' => 'What country has the most population?', 'answer' => 'India (as of 2023)'],
            ['question' => 'What is the capital of Egypt?', 'answer' => 'Cairo'],
            ['question' => 'What is the second longest river in the world?', 'answer' => 'The Amazon River'],
            ['question' => 'What is the capital of Spain?', 'answer' => 'Madrid'],
            ['question' => 'What strait separates Africa from Europe?', 'answer' => 'The Strait of Gibraltar'],
            ['question' => 'What is the capital of Russia?', 'answer' => 'Moscow'],
            ['question' => 'What is the largest island in the world?', 'answer' => 'Greenland'],
            ['question' => 'What is the capital of Germany?', 'answer' => 'Berlin'],
            ['question' => 'What sea is the saltiest body of water on Earth?', 'answer' => 'The Dead Sea'],
            ['question' => 'What is the capital of Italy?', 'answer' => 'Rome'],
            ['question' => 'What is the highest waterfall in the world?', 'answer' => 'Angel Falls in Venezuela'],
            ['question' => 'What is the capital of China?', 'answer' => 'Beijing'],
            ['question' => 'What country has the most islands?', 'answer' => 'Sweden (over 267,000 islands)'],
            ['question' => 'What is the capital of India?', 'answer' => 'New Delhi'],
            ['question' => 'What is the largest lake in the world by volume?', 'answer' => 'Lake Baikal in Russia'],
            ['question' => 'What is the capital of Mexico?', 'answer' => 'Mexico City'],
            ['question' => 'What is the driest place on Earth?', 'answer' => 'The Atacama Desert in Chile'],
            ['question' => 'What is the capital of Greece?', 'answer' => 'Athens'],
            ['question' => 'What is the longest mountain range in the world?', 'answer' => 'The Andes'],
            ['question' => 'What is the capital of South Korea?', 'answer' => 'Seoul'],
            ['question' => 'What is the largest freshwater lake by surface area?', 'answer' => 'Lake Superior'],
            ['question' => 'What is the capital of Argentina?', 'answer' => 'Buenos Aires'],
            ['question' => 'What country is known as the Land of the Rising Sun?', 'answer' => 'Japan'],
            ['question' => 'What is the capital of Turkey?', 'answer' => 'Ankara'],
            ['question' => 'What is the largest rainforest in the world?', 'answer' => 'The Amazon Rainforest'],
            ['question' => 'What is the capital of Sweden?', 'answer' => 'Stockholm'],
            ['question' => 'What is the highest capital city in the world?', 'answer' => 'La Paz, Bolivia'],
            ['question' => 'What is the capital of Norway?', 'answer' => 'Oslo'],
            ['question' => 'What city is known as the Eternal City?', 'answer' => 'Rome'],
            ['question' => 'What is the capital of Portugal?', 'answer' => 'Lisbon'],
            ['question' => 'What is the largest bay in the world?', 'answer' => 'The Bay of Bengal'],
            ['question' => 'What is the capital of Thailand?', 'answer' => 'Bangkok'],
            ['question' => 'What is the most densely populated country?', 'answer' => 'Monaco'],
            ['question' => 'What is the capital of Switzerland?', 'answer' => 'Bern'],
            ['question' => 'What is the coldest continent on Earth?', 'answer' => 'Antarctica'],
            ['question' => 'What is the capital of New Zealand?', 'answer' => 'Wellington'],

            // Pop Culture & Entertainment (151-200)
            ['question' => 'Who played Iron Man in the Marvel Cinematic Universe?', 'answer' => 'Robert Downey Jr.'],
            ['question' => 'What is the best-selling album of all time?', 'answer' => 'Thriller by Michael Jackson'],
            ['question' => 'Who wrote the Harry Potter series?', 'answer' => 'J.K. Rowling'],
            ['question' => 'What is the highest-grossing film of all time?', 'answer' => 'Avatar (2009)'],
            ['question' => 'Who is known as the King of Rock and Roll?', 'answer' => 'Elvis Presley'],
            ['question' => 'What TV show features the characters Chandler, Ross, and Rachel?', 'answer' => 'Friends'],
            ['question' => 'Who sang "Like a Virgin"?', 'answer' => 'Madonna'],
            ['question' => 'What is the longest-running Broadway show?', 'answer' => 'The Phantom of the Opera'],
            ['question' => 'Who played Jack Dawson in Titanic?', 'answer' => 'Leonardo DiCaprio'],
            ['question' => 'What band was Freddie Mercury the lead singer of?', 'answer' => 'Queen'],
            ['question' => 'What movie won the first Academy Award for Best Picture?', 'answer' => 'Wings (1927)'],
            ['question' => 'Who is known as the Queen of Pop?', 'answer' => 'Madonna'],
            ['question' => 'What is the name of the coffee shop in Friends?', 'answer' => 'Central Perk'],
            ['question' => 'Who wrote the novel "1984"?', 'answer' => 'George Orwell'],
            ['question' => 'What is the best-selling video game of all time?', 'answer' => 'Minecraft'],
            ['question' => 'Who directed The Godfather?', 'answer' => 'Francis Ford Coppola'],
            ['question' => 'What band performed "Stairway to Heaven"?', 'answer' => 'Led Zeppelin'],
            ['question' => 'What is the name of the fictional African country in Black Panther?', 'answer' => 'Wakanda'],
            ['question' => 'Who wrote "To Kill a Mockingbird"?', 'answer' => 'Harper Lee'],
            ['question' => 'What is the highest-selling single of all time?', 'answer' => '"White Christmas" by Bing Crosby'],
            ['question' => 'Who played Forrest Gump?', 'answer' => 'Tom Hanks'],
            ['question' => 'What is Eminem\'s real name?', 'answer' => 'Marshall Bruce Mathers III'],
            ['question' => 'What TV show is set in the fictional town of Hawkins, Indiana?', 'answer' => 'Stranger Things'],
            ['question' => 'Who painted "The Starry Night"?', 'answer' => 'Vincent van Gogh'],
            ['question' => 'What is the name of the hobbit played by Elijah Wood in Lord of the Rings?', 'answer' => 'Frodo Baggins'],
            ['question' => 'Who sang "Respect"?', 'answer' => 'Aretha Franklin'],
            ['question' => 'What is the name of the serial killer in the Halloween movies?', 'answer' => 'Michael Myers'],
            ['question' => 'Who wrote "Pride and Prejudice"?', 'answer' => 'Jane Austen'],
            ['question' => 'What is the name of the kingdom where Frozen takes place?', 'answer' => 'Arendelle'],
            ['question' => 'Who was the lead singer of Nirvana?', 'answer' => 'Kurt Cobain'],
            ['question' => 'What is the name of the possessed doll in The Conjuring series?', 'answer' => 'Annabelle'],
            ['question' => 'Who wrote "The Great Gatsby"?', 'answer' => 'F. Scott Fitzgerald'],
            ['question' => 'What is the name of Thor\'s hammer?', 'answer' => 'Mjolnir'],
            ['question' => 'Who sang "Rolling in the Deep"?', 'answer' => 'Adele'],
            ['question' => 'What is the name of the main character in The Matrix?', 'answer' => 'Neo (Thomas Anderson)'],
            ['question' => 'Who wrote "Frankenstein"?', 'answer' => 'Mary Shelley'],
            ['question' => 'What is the name of the wizarding school in Harry Potter?', 'answer' => 'Hogwarts School of Witchcraft and Wizardry'],
            ['question' => 'Who performed at the Super Bowl halftime show in 2020?', 'answer' => 'Shakira and Jennifer Lopez'],
            ['question' => 'What is the name of the dragon in The Hobbit?', 'answer' => 'Smaug'],
            ['question' => 'Who sang "I Will Always Love You"?', 'answer' => 'Whitney Houston'],
            ['question' => 'What is the name of Batman\'s butler?', 'answer' => 'Alfred Pennyworth'],
            ['question' => 'Who wrote "Romeo and Juliet"?', 'answer' => 'William Shakespeare'],
            ['question' => 'What is the name of Voldemort\'s snake?', 'answer' => 'Nagini'],
            ['question' => 'Who sang "Bohemian Rhapsody"?', 'answer' => 'Queen'],
            ['question' => 'What is the name of the fictional planet in Avatar?', 'answer' => 'Pandora'],
            ['question' => 'Who wrote "The Catcher in the Rye"?', 'answer' => 'J.D. Salinger'],
            ['question' => 'What is Superman\'s weakness?', 'answer' => 'Kryptonite'],
            ['question' => 'Who sang "Purple Rain"?', 'answer' => 'Prince'],
            ['question' => 'What is the name of the school in Grease?', 'answer' => 'Rydell High School'],
            ['question' => 'Who wrote "The Chronicles of Narnia"?', 'answer' => 'C.S. Lewis'],

            // Technology & Innovation (201-230)
            ['question' => 'Who founded Apple?', 'answer' => 'Steve Jobs, Steve Wozniak, and Ronald Wayne'],
            ['question' => 'What does HTTP stand for?', 'answer' => 'HyperText Transfer Protocol'],
            ['question' => 'What year was Google founded?', 'answer' => '1998'],
            ['question' => 'Who is the founder of Facebook?', 'answer' => 'Mark Zuckerberg'],
            ['question' => 'What does AI stand for?', 'answer' => 'Artificial Intelligence'],
            ['question' => 'What is the most popular programming language in 2024?', 'answer' => 'Python'],
            ['question' => 'What company developed the iPhone?', 'answer' => 'Apple Inc.'],
            ['question' => 'What does VR stand for?', 'answer' => 'Virtual Reality'],
            ['question' => 'Who invented the World Wide Web?', 'answer' => 'Tim Berners-Lee'],
            ['question' => 'What year was Twitter (now X) founded?', 'answer' => '2006'],
            ['question' => 'What does CPU stand for?', 'answer' => 'Central Processing Unit'],
            ['question' => 'Who is the CEO of Tesla?', 'answer' => 'Elon Musk'],
            ['question' => 'What is the most visited website in the world?', 'answer' => 'Google'],
            ['question' => 'What does RAM stand for?', 'answer' => 'Random Access Memory'],
            ['question' => 'What year was YouTube founded?', 'answer' => '2005'],
            ['question' => 'What is the largest social media platform?', 'answer' => 'Facebook'],
            ['question' => 'What does USB stand for?', 'answer' => 'Universal Serial Bus'],
            ['question' => 'Who founded Microsoft?', 'answer' => 'Bill Gates and Paul Allen'],
            ['question' => 'What is the most popular operating system for mobile devices?', 'answer' => 'Android'],
            ['question' => 'What does PDF stand for?', 'answer' => 'Portable Document Format'],
            ['question' => 'What year was Amazon founded?', 'answer' => '1994'],
            ['question' => 'What is the currency of cryptocurrency Bitcoin?', 'answer' => 'Bitcoin (BTC)'],
            ['question' => 'What does URL stand for?', 'answer' => 'Uniform Resource Locator'],
            ['question' => 'Who founded Tesla Motors?', 'answer' => 'Martin Eberhard and Marc Tarpenning (Elon Musk joined later)'],
            ['question' => 'What is the name of Apple\'s virtual assistant?', 'answer' => 'Siri'],
            ['question' => 'What does GPU stand for?', 'answer' => 'Graphics Processing Unit'],
            ['question' => 'What year was Instagram launched?', 'answer' => '2010'],
            ['question' => 'What is the most popular streaming service?', 'answer' => 'Netflix'],
            ['question' => 'What does Wi-Fi stand for?', 'answer' => 'Wireless Fidelity'],
            ['question' => 'Who founded SpaceX?', 'answer' => 'Elon Musk'],

            // Sports (231-260)
            ['question' => 'How many players are on a soccer team?', 'answer' => '11 players per team on the field'],
            ['question' => 'What sport is known as "The Beautiful Game"?', 'answer' => 'Soccer (football)'],
            ['question' => 'How many points is a touchdown worth in American football?', 'answer' => '6 points'],
            ['question' => 'What is the diameter of a basketball hoop?', 'answer' => '18 inches'],
            ['question' => 'How many Grand Slam tournaments are there in tennis?', 'answer' => 'Four (Australian Open, French Open, Wimbledon, US Open)'],
            ['question' => 'What country has won the most FIFA World Cups?', 'answer' => 'Brazil (5 times)'],
            ['question' => 'How many innings are in a baseball game?', 'answer' => '9 innings'],
            ['question' => 'What is the national sport of Canada?', 'answer' => 'Lacrosse (summer) and Ice Hockey (winter)'],
            ['question' => 'How many rings are on the Olympic flag?', 'answer' => 'Five rings'],
            ['question' => 'What is the maximum score in a single frame of bowling?', 'answer' => '30 (three strikes)'],
            ['question' => 'How many holes are on a standard golf course?', 'answer' => '18 holes'],
            ['question' => 'What is the only sport to be played on the moon?', 'answer' => 'Golf'],
            ['question' => 'How many players are on a basketball team on the court?', 'answer' => '5 players per team'],
            ['question' => 'What country won the first FIFA World Cup?', 'answer' => 'Uruguay in 1930'],
            ['question' => 'How many meters is an Olympic swimming pool?', 'answer' => '50 meters'],
            ['question' => 'What is the term for three strikes in a row in bowling?', 'answer' => 'A turkey'],
            ['question' => 'How many points is a field goal worth in basketball?', 'answer' => '2 or 3 points depending on distance'],
            ['question' => 'What country hosted the first modern Olympics?', 'answer' => 'Greece in 1896'],
            ['question' => 'How many bases are on a baseball field?', 'answer' => 'Four bases (including home plate)'],
            ['question' => 'What is the national sport of Japan?', 'answer' => 'Sumo wrestling'],
            ['question' => 'How many players are on a volleyball team?', 'answer' => '6 players per team on the court'],
            ['question' => 'What is the maximum break in snooker?', 'answer' => '147 points'],
            ['question' => 'How many periods are in a hockey game?', 'answer' => 'Three periods'],
            ['question' => 'What is the oldest tennis tournament in the world?', 'answer' => 'Wimbledon'],
            ['question' => 'How many players are on a rugby team?', 'answer' => '15 players per team (Rugby Union)'],
            ['question' => 'What country has won the most Olympic gold medals?', 'answer' => 'The United States'],
            ['question' => 'How many laps is the Indianapolis 500?', 'answer' => '200 laps'],
            ['question' => 'What is the fastest recorded serve in tennis?', 'answer' => '163.7 mph by Sam Groth'],
            ['question' => 'How many players are in a cricket team?', 'answer' => '11 players per team'],
            ['question' => 'What sport uses a puck instead of a ball?', 'answer' => 'Ice hockey'],

            // General Knowledge (261-300)
            ['question' => 'What is the largest mammal in the world?', 'answer' => 'The blue whale'],
            ['question' => 'How many colors are in a rainbow?', 'answer' => 'Seven colors'],
            ['question' => 'What is the fastest land animal?', 'answer' => 'The cheetah'],
            ['question' => 'How many days are in a leap year?', 'answer' => '366 days'],
            ['question' => 'What is the tallest building in the world?', 'answer' => 'Burj Khalifa in Dubai'],
            ['question' => 'How many seconds are in an hour?', 'answer' => '3,600 seconds'],
            ['question' => 'What is the smallest bone in the human body?', 'answer' => 'The stapes in the ear'],
            ['question' => 'How many stripes are on the American flag?', 'answer' => '13 stripes'],
            ['question' => 'What is the national flower of Japan?', 'answer' => 'Cherry blossom (sakura)'],
            ['question' => 'How many sides does a hexagon have?', 'answer' => 'Six sides'],
            ['question' => 'What is the largest bird in the world?', 'answer' => 'The ostrich'],
            ['question' => 'How many minutes are in a day?', 'answer' => '1,440 minutes'],
            ['question' => 'What is the national animal of Australia?', 'answer' => 'The kangaroo'],
            ['question' => 'How many zeros are in a million?', 'answer' => 'Six zeros'],
            ['question' => 'What is the most spoken language in the world?', 'answer' => 'English (by total speakers including non-native)'],
            ['question' => 'How many degrees are in a circle?', 'answer' => '360 degrees'],
            ['question' => 'What is the largest cat species?', 'answer' => 'The tiger'],
            ['question' => 'How many legs does a spider have?', 'answer' => 'Eight legs'],
            ['question' => 'What is the currency of the United Kingdom?', 'answer' => 'Pound Sterling (GBP)'],
            ['question' => 'How many centimeters are in a meter?', 'answer' => '100 centimeters'],
            ['question' => 'What is the fastest bird in the world?', 'answer' => 'The peregrine falcon'],
            ['question' => 'How many feet are in a mile?', 'answer' => '5,280 feet'],
            ['question' => 'What is the largest rodent in the world?', 'answer' => 'The capybara'],
            ['question' => 'How many teeth does an adult human have?', 'answer' => '32 teeth'],
            ['question' => 'What is the most expensive spice in the world?', 'answer' => 'Saffron'],
            ['question' => 'How many days are in February during a non-leap year?', 'answer' => '28 days'],
            ['question' => 'What is the largest snake in the world?', 'answer' => 'The green anaconda'],
            ['question' => 'How many keys are on a standard piano?', 'answer' => '88 keys'],
            ['question' => 'What is the most consumed beverage in the world?', 'answer' => 'Water'],
            ['question' => 'How many sides does a pentagon have?', 'answer' => 'Five sides'],
            ['question' => 'What is the largest shark species?', 'answer' => 'The whale shark'],
            ['question' => 'How many grams are in a kilogram?', 'answer' => '1,000 grams'],
            ['question' => 'What is the deadliest animal to humans?', 'answer' => 'The mosquito'],
            ['question' => 'How many states are in the United States?', 'answer' => '50 states'],
            ['question' => 'What is the largest lizard in the world?', 'answer' => 'The Komodo dragon'],
            ['question' => 'How many ounces are in a pound?', 'answer' => '16 ounces'],
            ['question' => 'What is the only mammal that can fly?', 'answer' => 'The bat'],
            ['question' => 'How many milliliters are in a liter?', 'answer' => '1,000 milliliters'],
            ['question' => 'What is the national bird of the United States?', 'answer' => 'The bald eagle'],
            ['question' => 'How many years are in a decade?', 'answer' => '10 years'],
        ];

        foreach ($questions as $index => $questionData) {
            SimpleQuestion::create([
                'question' => $questionData['question'],
                'answer' => $questionData['answer'],
                'active_date' => today(),
                'display_order' => $index + 1,
                'is_active' => true,
                'period_type' => 'daily',
            ]);
        }
    }
}
